# ASLAM Stereo camera:
# "Localization and Path Planning of a Climbing Robot for Corrosion Monitoring",
# Hannes Keller, Semester Project, ETH Zurich, 2014.
sensor_processor:
  type: stereo
  p_1:   0.03287
  p_2:  -0.0001276
  p_3:   0.4850
  p_4: 399.1046
  p_5:   0.000006735
  lateral_factor: 0.001376915
  depth_to_disparity_factor: 47.3
