# Written by Lefteris kotsonis.
# Modeling Fotonic G45 Sensor Noise for Improved 3D Reconstruction and Tracking.
sensor_processor:
  type: structured_light
  cutoff_min_depth: 0.5
  cutoff_max_depth: 3.25
  normal_factor_a: 0.0263
  normal_factor_b:  0
  normal_factor_c: 0
  normal_factor_d: 0
  normal_factor_e: 1
  lateral_factor: 0.003163
