# Manual tuned for uncalibrated PrimeSense Carmine 1.09.
# Also includes uncertainties with non perpedicular surfaces and
# biases/warp at further distances.
# Coefficients for lateral model taken from kinect_nguyen_et_al.yaml
sensor_processor:
  type: structured_light
  cutoff_min_depth: 0.2
  cutoff_max_depth: 2.0
  normal_factor_a: 0.003
  normal_factor_b: 0.015
  normal_factor_c: 0.25
  lateral_factor: 0.04
