# Written by Takahiro Miki.
# Modeling Realsense ZR300 Sensor Noise for Improved 3D Reconstruction and Tracking.
sensor_processor:
  type: structured_light
  cutoff_min_depth: 0.35
  cutoff_max_depth: 3.0
  normal_factor_a: 0.00241809
  normal_factor_b: 0.00662547
  normal_factor_c: 0.77199589
  normal_factor_d: 0
  normal_factor_e: 1
  lateral_factor: 0.00220941
